# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Apache Pirk (incubating)
email: dev@pirk.incubator.apache.org
description: > # this means to ignore newlines until "baseurl:"
  Pirk is a framework for scalable Private Information Retrieval (PIR).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pirk.incubator.apache.org" # the base hostname & protocol for your site
twitter_username: ApachePirk
github_username:  apache/pirk
repository: apache/incubator-pirk
exclude: [vendor]
latest_minor_release: XX

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "skeleton"

whitelist: [jekyll-redirect-from]
gems: [jekyll-redirect-from]
